"""add user_id to a task

Revision ID: 4abe28ebbd42
Revises: 
Create Date: 2026-05-25 22:40:44.513639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abe28ebbd42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_task', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_task', type_='foreignkey')
    op.drop_column('user_task', 'user_id')
    # ### end Alembic commands ###
